2021-10-23T21:22:48,487 Using pip 20.3.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
2021-10-23T21:22:48,489 Defaulting to user installation because normal site-packages is not writeable
2021-10-23T21:22:48,586 Created temporary directory: /tmp/pip-ephem-wheel-cache-i7b9jzb8
2021-10-23T21:22:48,586 Created temporary directory: /tmp/pip-req-tracker-c85zy24v
2021-10-23T21:22:48,586 Initialized build tracking at /tmp/pip-req-tracker-c85zy24v
2021-10-23T21:22:48,586 Created build tracker: /tmp/pip-req-tracker-c85zy24v
2021-10-23T21:22:48,586 Entered build tracker: /tmp/pip-req-tracker-c85zy24v
2021-10-23T21:22:48,586 Created temporary directory: /tmp/pip-install-sy_td7li
2021-10-23T21:22:48,586 ERROR: You must give at least one requirement to install (see "pip help install")
2021-10-23T21:22:48,587 Exception information:
2021-10-23T21:22:48,587 Traceback (most recent call last):
2021-10-23T21:22:48,587   File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
2021-10-23T21:22:48,587     status = self.run(options, args)
2021-10-23T21:22:48,587   File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
2021-10-23T21:22:48,587     return func(self, options, args)
2021-10-23T21:22:48,587   File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 291, in run
2021-10-23T21:22:48,587     reqs = self.get_requirements(args, options, finder, session)
2021-10-23T21:22:48,587   File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 391, in get_requirements
2021-10-23T21:22:48,587     raise CommandError(
2021-10-23T21:22:48,587 pip._internal.exceptions.CommandError: You must give at least one requirement to install (see "pip help install")
2021-10-23T21:22:48,711 Removed build tracker: '/tmp/pip-req-tracker-c85zy24v'
